apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  env: dev  

patches:
  - target:
      kind: Deployment
      name: moon-music
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: dev
  - target:
      kind: Deployment
      name: moon-music
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/image
        value: phuongcat02/moon-music:0.2-dev
